# Generated by Django 4.2.14 on 2024-12-06 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_gender_user_gender_alter_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocrfile', '0002_alter_folder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='account.company'),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
